### ISSUE TITLE
Error: reading EC2 Instance - Invalid address to set: []string{"root_block_device", "0", "tags_all"}

### ISSUE THREAD

**Issue by sudoFerraz** [bitovi/github-actions-deploy-docker-to-ec2#152]
Since 1 day ago, we are receiving the following error on all runs of the action:

`Error: reading EC2 Instance - Invalid address to set: []string{"root_block_device", "0", "tags_all"}`

Full logs can be found here: https://productionresultssa4.blob.core.windows.net/actions-results/75e2b857-2ef1-452c-81d0-1568e33f482f/workflow-job-run-974af46c-b22c-5f15-339d-00e4dd2ef2b8/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-03-02T07%3A59%3A12Z&sig=5MaXDRsbBRlGz4xb%2FA02G20qf3iw2ivE6ZGyasemKrs%3D&sp=r&spr=https&sr=b&st=2024-03-02T07%3A49%3A07Z&sv=2021-12-02

Link to an action failing on an open source repo: https://github.com/armitage-labs/armitage-monorepo/actions/runs/8121341921/job/22199578324

Tagging @LeoDiazL due to existing discord thread from other users experiencing the same; Discord thread: https://discord.com/channels/1007137664606150746/1213077630216048660/1213077630216048660

**Comment by gozmozdony** [comment]
It's an issue with the latest version of [hashicorp/terraform-provider-aws.](https://github.com/hashicorp/terraform-provider-aws).

https://github.com/hashicorp/terraform-provider-aws/issues/36038

It's been fixed in the next version: https://github.com/hashicorp/terraform-provider-aws/milestone/374?closed=1

**Comment by Crismon96** [comment]
@gozmozdony Running my actions still fails. Is there anything I need to configure or do I need to wait for a fix on the `[github-actions-deploy-docker-to-ec2](https://github.com/bitovi/github-actions-deploy-docker-to-ec2)` repo?

**Comment by gozmozdony** [comment]
@Crismon96  My educated guess would be that this repo consumes the latest version, so I think it's up to the terraform team to release the fixed version.

**Comment by LeoDiazL** [comment]
@sudoFerraz @gozmozdony @Crismon96 
Thank you all for your inputs! It's always good to hear and see involvement from the community. 

I've just went through some successful tests. The bug reported by @gozmozdony was the culprit. 

We'll add the option to set the desire provider version in future releases, as requested by @Crismon96 [here](https://github.com/bitovi/github-actions-deploy-docker-to-ec2/issues/153)

Feel free to add a message there if you want to keep track of the resolution of it. 

Once again, thanks for your inputs!
